language: node_js
node_js:
    - "0.10"
before_script:
    - npm install -g component@0.19.9
    - npm install -g mocha-phantomjs
    - component install
    - component build
notifications:
    slack:
        rooms:
            - gohone:k6kkTNlonb8PrSUb890lrpC5#tech
